### ISSUE TITLE
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by lzk98** [HIT-ImmunologyLab/PHISDetector#2]
Dear author
When I run the `PHIS --input < file path> --output <folder name >`,  get the error follow
```
[265304] Failed to execute script PHIS_overall_phage_to_host_two_criteria
Traceback (most recent call last):
  File "PHIS_overall_phage_to_host_two_criteria.py", line 12, in <module>
  File "/root/miniconda3/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/sklearn/__init__.py", line 76, in <module>
  File "/root/miniconda3/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/sklearn/base.py", line 16, in <module>
  File "/root/miniconda3/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/sklearn/utils/__init__.py", line 13, in <module>
  File "/root/miniconda3/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/scipy/sparse/__init__.py", line 230, in <module>
  File "/root/miniconda3/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/scipy/sparse/csr.py", line 13, in <module>
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/_MEItc8jz4/libstdc++.so.6)
```
 This error disappears when running `--model crispr/prophage/protein_protein_interaction/blast` separately.

Try to install GLIBC_2.18 ,as follows
```
wget http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.gz
tar zxf glibc-2.18.tar.gz 
cd glibc-2.18/
mkdir build
cd build/
../configure --prefix=/usr
make -j2
make install
```
However, the installation was not successful due to the lack of `autoconf`, which requires administrator privileges.

Is there a version that does not require `GLIBC_2.18`?

**Comment by LoreVE** [comment]
I encountered the same error. I would love to try out this tool, so any help would be greatly appreciated
